### ISSUE TITLE
Security issue with WebRTC Magic shared links?

### ISSUE THREAD

**Issue by bobbeims** [tradel/hassio-addons#3]
I've created links using the add-on UI > Links > WebRTC Magic section. I see that the generated links are in the form of 

```html
https://alexxit.github.io/go2rtc/#share=<GUID>&media=video+audio
``` 

Does this mean I'm exposing my camera streams URLs to some sort of cloud db that could potentially be breached?

**Comment by tradel** [comment]
I've never used the WebRTC Magic addon, so I can't speak to it. I
configured my camera URLs directly in Lovelace.

Note that your camera streams are *already* in the cloud. Abode sends all
of the video to Amazon KVS for processing. Go2rtc is fetching the streams
from Amazon, not directly from your camera.

**Comment by bobbeims** [comment]
Thanks for that reminder. As a computer system architect with 40 years of experience, I'm embarrassed that I didn't intuitively jump to that conclusion. Offloading all of the image processing to AWS is the only way Abode can keep the cost of the Cam 2 so low.

**Comment by tradel** [comment]
No worries. And on the plus side, we got to learn a bit about Amazon
Kinesis!


Todd Radel

[image: icon] +1 (484) 557-5699 <+1(484)557-5699>   [image: icon]
links.tradel.me

[image: icon] ***@***.***

[image: github] <https://github.com/tradel>

[image: threads] <https://threads.net/toddradel>

[image: facebook] <https://facebook.com/todd.radel>

[image: instagram] <https://instagram.com/toddradel/>

[image: linkedin] <https://linkedin.com/in/tradel/>

[image: twitter] <https://twitter.com/tradel>
[image: photo] <https://links.tradel.me>

[image: __tpx__]
